# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
 branches:
    master:
      - step:
          name: Deploy to GITHUB
          deployment: GITHUB
          script:
            - echo "Deploying to GITHUB"
            - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
            - git push git@github.com:guardamelugar/guardame-lugar.git
