export const URL_SIGNUP = 'http://localhost:50500/guardamelugar/clientes/signup'
export const URL_LOGIN = 'http://localhost:50500/guardamelugar/clientes/login'
export const URL_REGISTER_GARAGE = 'http://localhost:50500/guardamelugar/garages/garageregister'
export const URL_LOCALIDADES = 'http://localhost:50500/guardamelugar/garages/localidades'
export const URL_GARAGE_USUARIO = 'http://localhost:50500/guardamelugar/garages/user/'